#!/bin/bash
#creating files
touch -t 202103081800 foo
touch -t 202103081801 goo
touch -t 202103081802 hoo

# creating older.sh
vi older.sh

ls -lt | tail -1

# to make file public
chmod u+x older.sh

# to check the output
./older.sh


